title: The SSO Wall of Shame
description: >-
  A list of vendors that treat single sign-on as a luxury feature, not a core
  security requirement.

url: https://ssotax.org

github_url: https://github.com/ssotax/ssotax

kramdown:
  parse_block_html: true

collections:
  - vendors_bad
  - vendors_good
