title: The SSO Wall of Shame
description: >-
  A list of vendors that treat single sign-on as a luxury feature, not a core
  security requirement.

url: https://ssotax.github.io/ssotax
baseurl: https://ssotax.github.io/ssotax

kramdown:
  parse_block_html: true

collections:
  - vendors
